version: "3"

services:
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: ./apps/app1/Dockerfile
    restart: always
    ports:
      - "3001:3000"
    networks:
      - app_network

  app2:
    container_name: app2
    build:
      context: .
      dockerfile: ./apps/app2/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    networks:
      - app_network

  
networks:
  app_network:
    driver: bridge
